### ISSUE TITLE
Failure on prepare() on Manjaro

### ISSUE THREAD

**Issue by elliott-maguire** [wsdfhjxc/xfce-patches#4]
Currently running XFCE Manjaro, xfwm4 wrapped in by default, and when I try to install the xfwm4-rounded-corners patch from AUR through pamac, I get the following failure after it switches to xfwm4-4.14.0:

    error: can't open patch '/var/tmp/pamac-build-e/xfwm4-rounded-corners/src/xfwm-rounded-corners-patch/xfwm-4.14.0-rounded-corners.patch': No such file or directory
    ==> ERROR: A failure occurred in prepare().
        Aborting...

But, if I check that directory, the patch is right there. Any ideas?

**Comment by hisacro** [comment]
if I'm not wrong you will find "xfwm4-4.14.0-rounded-corners.patch"  there, rename it good to go

**Comment by wsdfhjxc** [comment]
I didn't even know that someone published an AUR package for the rounded corners patch. As I've reorganized the repository and threw in more patches, the file got renamed. However, I have no control over the AUR package, so you have to contact the package maintainer to update it.

**Comment by hisacro** [comment]
hey @wsdfhjxc It worked fine for me but bit of rough pixels, guess I need to tinker around
