### ISSUE TITLE
No such file or repo

### ISSUE THREAD

**Issue by Lanhild** [wsdfhjxc/xfce-patches#6]
`~/xfwm4/src$ ./src/xfwm4 --replace & disown` 
`[1] 96291`
`~/xfwm4/src$ bash: ./src/xfwm4: No such file or directory`

How can I solve that? @wsdfhjxc

**Comment by wsdfhjxc** [comment]
It looks like you're already inside the `xfwm4/src` directory. The instructions have been written in assumption that the user does not `cd` to directories in-between steps, so you must be cautious about the current location and relative paths in the instructions.

Just enter the directory where you have cloned the xfwm4's source code. Then, one by one, execute commands from the instructions, and do not `cd` to any other directories inside, so the mentioned paths are relative to your current location.

```
cd xfwm4
git checkout xfwm4-4.14.0

LIBDIRPATH=/usr/lib/x86_64-linux-gnu
./autogen.sh --prefix=/usr --libdir=$LIBDIRPATH --libexecdir=$LIBDIRPATH && make

./src/xfwm4 --replace & disown
```

The instructions might not be much user-friendly (finding dependencies or `LIBDIRPATH` is on the user), but that's how it is.

**Comment by Lanhild** [comment]
Thanks a lot for your answer, I'll try it right away!

**Comment by Lanhild** [comment]
`~/xfwm4$ ./src/xfwm4 --replace & disown`
`[1] 96291`
`~/xfwm4$ bash: ./src/xfwm4: No such file or directory`

I got the exact same error, even though I am in ~/xfwm4...

**Comment by Lanhild** [comment]
Any clues?

**Comment by wsdfhjxc** [comment]
Are there any errors while running the mentioned earlier `./autogen.sh [...] && make` part to build the xfwm4 binary?

**Comment by Lanhild** [comment]
onfigure: error: expected an absolute directory name for --libexecdir:

**Comment by wsdfhjxc** [comment]
You need to run all commands, do not skip setting the `LIBDIRPATH` variable, it's important.

```
LIBDIRPATH=/usr/lib/x86_64-linux-gnu
```

The one above is for Ubuntu. It's different for other distributions. What is your distro?

And then, if the variable is set, you can execute the commands to build xfwm4:

```
./autogen.sh --prefix=/usr --libdir=$LIBDIRPATH --libexecdir=$LIBDIRPATH && make
```

Note that several development libraries are needed to be installed on the system before the code can be compiled. You'll have to check the output hints for missing libraries and install the required packages for the distro of your choice. It's a pain in the ass.

**Comment by Lanhild** [comment]
I am on Ubuntu, Thanks for your answer I'l try it again and will tell you if I have any other issues.
